name: build
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Test
      run: |
        go mod tidy -v
        go test -race ./...

    - name: Build
      run: go build ./...
